#!/usr/bin/env php
<?php

define('MAKELOS_STANDALONE', true);

defined('DS') || define('DS', DIRECTORY_SEPARATOR);
define('AK_BASE_DIR', $_SERVER['PWD']);
defined('AK_FRAMEWORK_DIR') || define('AK_FRAMEWORK_DIR', AK_BASE_DIR.DS.'vendor'.DS.'akelos');
define('MAKELOS_BASE_DIR', dirname(__FILE__));
defined('AK_TEST_DIR') || define('AK_TEST_DIR', MAKELOS_BASE_DIR.DS.'test');
define('AK_TESTING_NAMESPACE', 'plugins');

$GLOBALS['argv'][] = '--component=plugins';

if(!file_exists(AK_BASE_DIR.DS.'app'.DS.'controllers'.DS.'admin')){
    die("\nEditam need admin_plugin to be installed first.\nYou can add admin_plugin by running './script/plugin install admin'\n");
}

include AK_FRAMEWORK_DIR.DS.'akelos_utils'.DS.'makelos'.DS.'makelos.php';


